using MSSMS.DBHandler;
using MSSMS.Enums;
using MSSMS.Models;
using MSSMS.Utilities;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace MSSMS
{
    public partial class ReportViewerScheduledShipmentStatus : Form
    {
        private ReportType reportType = ReportType.NONE;
        private DateTime statDateTime = DateTime.MinValue;
        private DateTime endDateTime = DateTime.MinValue;
        private ReportsDBHandler reportsDBHandler = new ReportsDBHandler();
        private List<ShippingSchedule> shippingSchedules = new List<ShippingSchedule>();

        public ReportViewerScheduledShipmentStatus(ReportType reportType, DateTime startDateTime, DateTime endDateTime)
        {
            InitializeComponent();

            this.reportType = reportType;
            this.statDateTime = startDateTime;
            this.endDateTime = endDateTime;

            if (reportType == ReportType.MONTHLY)
            {
                generateMonthlyReport();
            }
        }

        private void ReportViewerScheduledShipmentStatus_Load(object sender, EventArgs e)
        {
            NotificationManager.hideInAppNotification(panelInAppNotifications);
        }

        private void btnCloseInAppNotification_Click(object sender, EventArgs e)
        {
            NotificationManager.hideInAppNotification(panelInAppNotifications);
        }

        private void generateMonthlyReport()
        {
            this.labelInfo.Text = "REPORT ISSUED ON: " + DateTime.Now + "\nREPORT GENERATED BY: " + SessionManager.user.employeeId + "\n\nREPORT TYPE: MONTHLY REPORT.\nMONTH: " + this.statDateTime.ToString("MM-yyyy");

            NotificationManager.hideInAppNotification(panelInAppNotifications);

            try
            {
                shippingSchedules = reportsDBHandler.getMonthlyShipmentStatusReport(this.statDateTime);
                dataGridReport.Rows.Clear();

                //binding
                foreach (ShippingSchedule shippingSchedule in shippingSchedules)
                {
                    String expStatus = null;
                    String approvalStatus = null;

                    if (ValidationHandler.IsBeforeDate(shippingSchedule.loading_date) && shippingSchedule.status == "Pending")
                    {
                        expStatus = "Expired";
                    }
                    else
                    {
                        expStatus = shippingSchedule.status;
                    }

                    if (shippingSchedule.approved_date == DateTime.MinValue || shippingSchedule.approved_by == "N/A")
                    {
                        approvalStatus = "Not Approved";
                    }
                    else
                    {
                        approvalStatus = "Approved";
                    }

                    dataGridReport.Rows.Add(shippingSchedule.shippingschedule_id, shippingSchedule.contract_no, shippingSchedule.destination, shippingSchedule.address, shippingSchedule.loading_date.ToShortDateString(), shippingSchedule.added_date, shippingSchedule.added_by, shippingSchedule.approved_date, approvalStatus, expStatus, shippingSchedule.oi_per_ss_count, shippingSchedule.total_mc_count);
                }
            }
            catch (MSSMUIException ex)
            {
                NotificationManager.showInAppNotification(panelInAppNotifications, lableInAppNotification, pbInAppNotification, btnCloseInAppNotification, ex.Message, NotificationStates.ERROR);
            }
            catch (Exception ex)
            {
                NotificationManager.showInAppNotification(panelInAppNotifications, lableInAppNotification, pbInAppNotification, btnCloseInAppNotification, ex.Message, NotificationStates.ERROR);
            }
        }

        private void btnPrint_Click(object sender, EventArgs e)
        {
            NotificationManager.hideInAppNotification(panelInAppNotifications);
            if (dataGridReport.Rows.Count > 0)
            {
                Microsoft.Office.Interop.Excel.Application excellApplication = new Microsoft.Office.Interop.Excel.Application();
                excellApplication.Application.Workbooks.Add(Type.Missing);

                for (int i = 0; i < dataGridReport.Columns.Count - 1; i++)
                {
                    try
                    {
                        excellApplication.Cells[1, i] = dataGridReport.Columns[i - 1].HeaderText;
                    }
                    catch (Exception ex)
                    {

                    }
                }

                for (int i = 0; i < dataGridReport.Rows.Count; i++)
                {
                    for (int j = 0; j < dataGridReport.Columns.Count - 2; j++)
                    {
                        excellApplication.Cells[i + 2, j + 1] = dataGridReport.Rows[i].Cells[j].Value.ToString();
                    }
                }
                excellApplication.Columns.AutoFit();
                excellApplication.Visible = true;

                NotificationManager.showInAppNotification(panelInAppNotifications, lableInAppNotification, pbInAppNotification, btnCloseInAppNotification, "Report Exported.", NotificationStates.SUCCESS);
            }
            else
            {
                NotificationManager.showInAppNotification(panelInAppNotifications, lableInAppNotification, pbInAppNotification, btnCloseInAppNotification, "Nothing to Export.", NotificationStates.INFORMATION);
            }
        }
    }
}
